export * from './get-callback-domain';
export * from './get-location-path-status';
export * from './i18n-module';
export * from './send-callback';
export * from './set-discount';
export * from './set-font-sizes';
export * from './set-iframe-events';
export * from './url-variables';
export * from './calculate-sale'
